name: fundza
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  animated_text_kit: ^4.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.2

flutter:
  uses-material-design: true
  assets:
    - assets/images/logo.png
    - assets/images/blog/blog1.jfif
    - assets/images/blog/blog2.jfif
    - assets/images/blog/blog1.jfif
    - assets/images/blog/blog3.jfif
    - assets/images/blog/blog3.jpeg
    - assets/images/blog/blog4.jfif
    - assets/images/blog/blog5.jfif
    - assets/images/blog/blog6.jfif
    - assets/images/blog/blog7.jpg
    - assets/images/blog/blog9.jpeg
    - assets/images/logo_small.png
  fonts:
    - family: Marcellus
      fonts:
        - asset: assets/fonts/Marcellus-Regular.ttf
  # assets:
  #  - images/a_dot_burr.jpeg
  #  - images/a_dot_ham.jpeg
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
